# Generated by Django 2.2.3 on 2019-07-25 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20190720_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='shot',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='price',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=8),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('old', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], max_length=11)),
                ('date', models.DateTimeField()),
                ('commands', models.ManyToManyField(to='api.Command')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='user_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.FloatField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Command')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='contributions',
            field=models.ManyToManyField(through='api.CommandContribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='command',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AddField(
            model_name='shot',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShotTrayCommand',
            fields=[
                ('command_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Command')),
                ('shots', models.ManyToManyField(to='api.Product')),
            ],
            bases=('api.command',),
        ),
    ]
