# Generated by Django 2.2.3 on 2019-08-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190725_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commandcontribution',
            name='part',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
