# Generated by Django 2.2.3 on 2019-08-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190803_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandcontribution',
            name='part',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
